# Generated by Django 5.1.2 on 2024-10-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_set', to='user_profile_app.userprofile')),
                ('following', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='user_profile_app.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('following', 'followed'), name='unique_follow')],
            },
        ),
    ]
