# Generated by Django 5.1.2 on 2024-10-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_twitter_app', '0002_remove_person_following_folow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folow',
            new_name='Follow',
        ),
    ]
