# Generated by Django 5.1.2 on 2024-10-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_twitter_app', '0003_rename_folow_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
