# Generated by Django 5.1.2 on 2024-10-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_twitter_app', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='system_user',
        ),
    ]
