# Generated by Django 5.1.2 on 2024-10-27 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_twitter_app', '0009_alter_userprofile_system_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='mini_twitter_app.post'),
        ),
    ]
